"""VNCDriver Protocol (plan.md drivers/base.py)."""

from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class VNCDriver(Protocol):
    async def connect(self) -> None: ...

    async def disconnect(self) -> None: ...

    async def reconnect(self) -> None: ...

    async def capture_screen(self) -> bytes:
        """Return PNG (or raw RGB) bytes of the full screen."""
        ...

    async def capture_region(self, x: int, y: int, w: int, h: int) -> bytes: ...

    async def send_key(self, key: str) -> None: ...

    async def send_hotkey(self, keys: list[str]) -> None: ...

    async def send_text(self, text: str) -> None: ...

    async def mouse_move(self, x: int, y: int) -> None: ...

    async def click(self, x: int, y: int, button: int = 1) -> None: ...

    async def double_click(self, x: int, y: int) -> None: ...

    async def right_click(self, x: int, y: int) -> None: ...

    async def scroll(self, x: int, y: int, direction: str, amount: int = 3) -> None: ...

    async def drag(
        self, x1: int, y1: int, x2: int, y2: int, button: int = 1
    ) -> None: ...

    @property
    def resolution(self) -> tuple[int, int]:
        """(width, height) of the connected desktop."""
        ...

    @property
    def connected(self) -> bool: ...
