#!/usr/bin/env python3
"""Feature 024 (FR-005c): draft an app-perception profile from a WinForms
designer file.

STRICTLY READ-ONLY with respect to the application source tree: this script
only reads `*.Designer.cs` and writes YAML to stdout (or a path you choose
inside THIS repository). It never writes anywhere near the app sources.

The output is a DRAFT. A human must review it before it is committed — see
"MANUAL REVIEW" in the emitted header and in profiles/app_perception/README.md.

Usage
-----
    python scripts/gen_app_profile_from_designer.py <Form.Designer.cs> \
        [--name my-window] [--anchors "Barcode:,Favorite:,TopMost"] \
        [-o profiles/app_perception/my-window.yaml]

    # inspect the parsed controls without producing a profile
    python scripts/gen_app_profile_from_designer.py <Form.Designer.cs> --list
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

_CLIENT_SIZE = re.compile(
    r"this\.ClientSize\s*=\s*new\s+System\.Drawing\.Size\((\d+),\s*(\d+)\)"
)
_FORM_TEXT = re.compile(r"this\.Text\s*=\s*\"([^\"]*)\"")
_ASSIGN = re.compile(r"this\.(\w+)\.(Location|Size|Text|Anchor)\s*=\s*([^;]+);")
_POINT = re.compile(r"Point\((-?\d+),\s*(-?\d+)\)")
_SIZE = re.compile(r"Size\((-?\d+),\s*(-?\d+)\)")
_LITERAL = re.compile(r'^"(.*)"$', re.S)
_ANCHOR = re.compile(r"AnchorStyles\.(\w+)")

# WinForms default when no Anchor is set.
_DEFAULT_ANCHORS = ("top", "left")


@dataclass
class Control:
    name: str
    text: str | None
    rect: tuple[int, int, int, int]
    anchors: tuple[str, ...]


def parse_designer(source: str) -> tuple[str | None, tuple[int, int] | None, list[Control]]:
    size_match = _CLIENT_SIZE.search(source)
    client_size = (
        (int(size_match.group(1)), int(size_match.group(2))) if size_match else None
    )
    title_match = _FORM_TEXT.search(source)
    title = title_match.group(1) if title_match else None

    raw: dict[str, dict[str, str]] = {}
    for match in _ASSIGN.finditer(source):
        name, prop, value = match.group(1), match.group(2), match.group(3).strip()
        raw.setdefault(name, {})[prop] = value

    controls: list[Control] = []
    for name, props in raw.items():
        loc, size = _POINT.search(props.get("Location", "")), _SIZE.search(props.get("Size", ""))
        if not (loc and size):
            continue
        x, y = int(loc.group(1)), int(loc.group(2))
        w, h = int(size.group(1)), int(size.group(2))
        if w <= 0 or h <= 0:
            continue
        text_literal = _LITERAL.match(props.get("Text", "").strip())
        text = text_literal.group(1) if text_literal else None
        anchors = tuple(sorted({a.lower() for a in _ANCHOR.findall(props.get("Anchor", ""))}))
        anchors = tuple(a for a in anchors if a in ("top", "bottom", "left", "right"))
        controls.append(
            Control(name=name, text=text or None, rect=(x, y, x + w, y + h),
                    anchors=anchors or _DEFAULT_ANCHORS)
        )
    controls.sort(key=lambda c: (c.rect[1], c.rect[0]))
    return title, client_size, controls


def _q(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_profile(
    *, name: str, title: str | None, client_size: tuple[int, int],
    controls: list[Control], anchors: list[str],
) -> str:
    lines = [
        "# DRAFT generated by scripts/gen_app_profile_from_designer.py",
        "#",
        "# MANUAL REVIEW REQUIRED before committing — check these five things:",
        "#   1. required_anchors: must be text that OCR actually reads on the",
        "#      live screen. Prefer ASCII / digits / kanji; the deployed OCR",
        "#      model garbles some kana. Pick anchors spread over the top,",
        "#      middle and bottom of the window so their union covers it.",
        "#   2. required_anchors must NOT contain text that also appears",
        "#      outside this window, or the union will be dragged off-window.",
        "#   3. Drop anchors whose text changes at runtime (table contents,",
        "#      counters, timestamps).",
        "#   4. source_geometry rects are DESIGN-TIME. They are never used as",
        "#      screen coordinates directly: at runtime a design->screen",
        "#      transform is solved from the anchors OCR actually measured, and",
        "#      gated on its residuals. Check the rects against the designer",
        "#      file, not against a screenshot.",
        "#   5. Controls with no Text are exported by Name — those are usually",
        "#      the ones worth targeting geometrically (bare input boxes).",
        "",
        f"name: {name}",
    ]
    if title:
        lines.append("description: >-")
        lines.append(f"  Design-time title: {title}")
    lines.append("")
    lines.append("required_anchors:")
    for anchor in anchors:
        lines.append(f"  - {_q(anchor)}")
    if title:
        lines.append(f"title_anchor: {_q(title)}")
    lines.append("")
    lines.append("source_geometry:")
    lines.append(f"  client_size: [{client_size[0]}, {client_size[1]}]")
    lines.append("  controls:")
    # Controls WITHOUT a literal Text are exported too, keyed by Name. Those
    # are exactly the ones geometry is needed for: a bare input box has no
    # text for OCR or a model to latch onto, so nothing else can locate it.
    for control in controls:
        x1, y1, x2, y2 = control.rect
        lines.append(f"    - name: {control.name}")
        if control.text:
            lines.append(f"      text: {_q(control.text)}")
        lines.append(f"      rect: [{x1}, {y1}, {x2}, {y2}]")
        lines.append(f"      anchors: [{', '.join(control.anchors)}]")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Draft an app-perception profile from a WinForms designer file "
                    "(read-only; never writes to the application source tree).",
    )
    parser.add_argument("designer", type=Path, help="path to a *.Designer.cs file")
    parser.add_argument("--name", help="profile name (default: derived from the form title)")
    parser.add_argument("--anchors", help="comma-separated required_anchors (default: first "
                                         "three literal control texts — REVIEW THESE)")
    parser.add_argument("-o", "--output", type=Path, help="write here instead of stdout")
    parser.add_argument("--list", action="store_true", help="list parsed controls and exit")
    args = parser.parse_args(argv)

    try:
        source = args.designer.read_text(encoding="utf-8", errors="replace")
    except OSError as exc:
        print(f"error: cannot read {args.designer}: {exc}", file=sys.stderr)
        return 2

    title, client_size, controls = parse_designer(source)
    if client_size is None:
        print(f"error: no ClientSize found in {args.designer}", file=sys.stderr)
        return 2

    if args.list:
        width, height = client_size
        print(f"title={title!r} client_size={width}x{height} controls={len(controls)}")
        for control in controls:
            x1, y1, x2, y2 = control.rect
            rel = f"({x1/width:.3f},{y1/height:.3f},{x2/width:.3f},{y2/height:.3f})"
            anchors = ",".join(control.anchors)
            print(f"  {control.name:24} {str(control.text):20} {rel} anchors={anchors}")
        return 0

    name = args.name or re.sub(r"[^a-z0-9]+", "-", (title or args.designer.stem).lower()).strip("-")
    if args.anchors:
        anchors = [a.strip() for a in args.anchors.split(",") if a.strip()]
    else:
        anchors = [c.text for c in controls if c.text][:3]
    if not anchors:
        print("error: no anchor candidates; pass --anchors explicitly", file=sys.stderr)
        return 2

    rendered = render_profile(
        name=name, title=title, client_size=client_size, controls=controls, anchors=anchors
    )
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(rendered, encoding="utf-8")
        print(f"wrote draft profile to {args.output} — REVIEW BEFORE COMMITTING", file=sys.stderr)
    else:
        sys.stdout.write(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
